services:
  - type: web
    name: ice-alert-backend
    env: node
    region: ohio
    buildCommand: |
      cd server
      npm install
    startCommand: |
      cd server
      echo "Applying schema and migrations..."
      node apply-schema.js &&
      echo "Starting server..."
      node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://aaaa-arduino-proj-9ievnvz20-icealerts-projects.vercel.app
      - key: NODE_ENV
        value: production

databases:
  - name: ice-alert-db
    plan: free
    ipAllowList: []