services:
  - type: web
    name: ice-alert-backend
    env: node
    region: ohio
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: https://xxdjtvevvszefsvgjwye.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGp0dmV2dnN6ZWZzdmdqd3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzQ4NTksImV4cCI6MjA0OTc1MDg1OX0.g4mULV_tFw_W6L_Iy1GxJuYm1O_tUt30Wuu7R1aNLuo
      - key: CORS_ORIGIN
        value: https://aaaa-arduino-proj-9ievnvz20-icealerts-projects.vercel.app
      - key: NODE_ENV
        value: production

databases:
  - name: ice-alert-db
    plan: free
    ipAllowList: [] 