services:
  - type: web
    name: ice-alert-backend
    env: node
    region: ohio
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: https://xxdjtvevszefsvgjwye.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGp0dmV2c3plZnN2Z2p3eWUiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTcxMDY5NzE5OCwiZXhwIjoyMDI2MjczMTk4fQ.Wd-GYHQPXMxWvBWXPqPgPBJvKEeqwdXMWKB_LB8qBkE
      - key: CORS_ORIGIN
        value: https://ice-alert-frontend1.vercel.app,https://aaaa-arduino-proj-9ievnvz20-icealerts-projects.vercel.app
      - key: EMAIL_USER
        value: icealertdevice@gmail.com
      - key: EMAIL_PASSWORD
        value: ygif qlfc qvll hhex

databases:
  - name: ice-alert-db
    plan: free
    ipAllowList: [] 