services:
  - type: web
    name: ice-alert-backend
    env: node
    region: ohio
    buildCommand: |
      cd server
      npm install
      echo "Running schema application..."
      export SUPABASE_URL=https://xxdjtvevvszefsvgjwye.supabase.co
      export SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGp0dmV2dnN6ZWZzdmdqd3llIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDE3NDg1OSwiZXhwIjoyMDQ5NzUwODU5fQ.Qbwr5OqyCUiw-fCZG3dx6pSKXDrqi1PObiIiJlpJqgc
      echo "Waiting for environment variables to propagate..."
      sleep 5
      node apply-schema.js || exit 1
      echo "Schema application completed"
    startCommand: |
      cd server
      echo "Starting server..."
      node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: https://xxdjtvevvszefsvgjwye.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGp0dmV2dnN6ZWZzdmdqd3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzQ4NTksImV4cCI6MjA0OTc1MDg1OX0.g4mULV_tFw_W6L_Iy1GxJuYm1O_tUt30Wuu7R1aNLuo
      - key: CORS_ORIGIN
        value: https://aaaa-arduino-proj-9ievnvz20-icealerts-projects.vercel.app
      - key: NODE_ENV
        value: production
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGp0dmV2dnN6ZWZzdmdqd3llIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDE3NDg1OSwiZXhwIjoyMDQ5NzUwODU5fQ.Qbwr5OqyCUiw-fCZG3dx6pSKXDrqi1PObiIiJlpJqgc

databases:
  - name: ice-alert-db
    plan: free
    ipAllowList: []