name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_nYMQ56pMnhe5Jjqk5SJ1gwg3zqqt/XSiRJUcB39

      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-ctemqopu0jms739dmjq0?key=C97EUaWtUaQ 